trigger:
- main

variables:
  AZURE_FUNCTIONAPP_NAME: 'GetResumeCounter2023'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  DOTNET_VERSION: '6.0'

jobs:
- job: build_and_deploy
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
      checkLatest: true

  - script: |
      az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
    displayName: 'Login via Azure CLI'
    
  - script: |
      cd $(AZURE_FUNCTIONAPP_PACKAGE_PATH)/api
      dotnet build --configuration Release --output ./output
    displayName: 'Build project'

  - script: |
      cd $(AZURE_FUNCTIONAPP_PACKAGE_PATH)/tests
      dotnet test
    displayName: 'Run tests'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure-Abonnement 1'
      appName: $(AZURE_FUNCTIONAPP_NAME)
      package: '$(AZURE_FUNCTIONAPP_PACKAGE_PATH)/api/output'
